---
name: trigger-deploy
on:
  push:
    branches:
      - main
jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt-get install -y discount htmlmin npm && npm i -g markmap-cli
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cd repo
        run: cd ${{ github.workspace }}
      - name: build
        run: make
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ github.workspace }}/build"
