---
name: trigger-deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y pandoc htmlmin npm
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: cd ${{ github.workspace }}
      - run: npm i
      - run: make
      - run: |
          tar \
          --directory "${{ github.workspace }}/build" \
          -cvf "$RUNNER_TEMP/artifact.tar" \
      - uses: actions/upload-artifact@main
        with:
          name: gh-pages
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@main
        with:
          name: gh-pages
          path: .
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@main
